[[redirects]]
  from = "http://suggestqueries.google.com/complete/search?client=chrome&ds=yt&q="
  to = "http://suggestqueries.google.com/complete/search?client=chrome&ds=yt&q="
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
